if(EXISTS "/mnt/c/RLOFEST/vowpal_wabbit/vowpalwabbit/slim/vw_slim_test[1]_tests.cmake")
  include("/mnt/c/RLOFEST/vowpal_wabbit/vowpalwabbit/slim/vw_slim_test[1]_tests.cmake")
else()
  add_test(vw_slim_test_NOT_BUILT vw_slim_test_NOT_BUILT)
endif()
