if(EXISTS "/mnt/c/RLOFEST/vowpal_wabbit/vowpalwabbit/core/vw_core_test[1]_tests.cmake")
  include("/mnt/c/RLOFEST/vowpal_wabbit/vowpalwabbit/core/vw_core_test[1]_tests.cmake")
else()
  add_test(vw_core_test_NOT_BUILT vw_core_test_NOT_BUILT)
endif()
